### ISSUE TITLE
Bug Finished outside the program

### ISSUE THREAD

**Issue by jovanzers** [AguzzTN54/gcsbhelper#3]
![image](https://github.com/user-attachments/assets/024ff58f-8ebc-4c11-a96c-9bb3abf699e7)
Sometimes it's not load correctly

**Comment by AguzzTN54** [comment]
I am currently investigating this issue.

Are you using a language other than English in your browser (for example, Indonesian)? If so, your issue is already on my radar, and a fix will be available soon.

**Comment by AguzzTN54** [comment]
Please reopen this issue if you are still facing this problem
